//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictorPicoYPlacaClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicoYPlaca
    {
        public int Id { get; set; }
        public int LicensePlateNumber { get; set; }
        public int IdDayOfWeek { get; set; }
    
        public virtual DayOfWeek DayOfWeek { get; set; }
    }
}
